name: file-changed

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  file-changed:
    runs-on: [ubuntu-latest]
    steps:
      - name: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done