name: file-changed

on:
  pull_request:
    branches:
      - develop

jobs:
  file-changed:
    runs-on: [ubuntu-latest]
    steps:
      - name: files
        id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          ts_files_count=0
          js_files_count=0
          echo "${{ steps.files.outputs.all }}"
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
            if  [[ "${changed_file}" == *.ts ]] || [[ "${changed_file}" == *.tsx ]]
            then
              ((ts_files_count=ts_files_count+1))
            elif [[ "${changed_file}" == *.js ]] || [[ "${changed_file}" == *.jsx ]]
            then
              ((js_files_count=js_files_count+1))
            fi
          done
          echo "Number of TS files: $ts_files_count"
          echo "Number of JS files: $js_files_count"
          if  [[ $ts_files_count -lt $js_files_count ]]
          then
            exit 1
          fi
